!ifndef VCREDIST_CONFIG
	!define VCREDIST_CONFIG
	!define VCREDIST_USE_INETC
	;!define VCREDIST_OFFLINEMODE

	!define	VCREDIST2005
	!define	VCREDIST2008
	!define VCREDIST2010
	!define	VCREDIST2012
	!define	VCREDIST2013
	!define	VCREDIST2015
	!define	VCREDIST2017
	!define	VCREDIST2019

	!define	VCREDIST_ROOT		""
	!define VCREDIST_COMMAND	"/q:a"
!endif